# fix commonmarker (0.17.13) issue: sudo apt install ruby-dev
# fix nokogiri (1.10.9) issue: sudo apt install zlib1g-dev
# For local testing, run:
# bundle exec jekyll serve --config _config.yml,_config-dev.yml
url: http://localhost:4000
